/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xoproject;

import javax.swing.JOptionPane;

/**
 *
 * @author saids
 */
public class mainframe extends javax.swing.JFrame {

    /**
     * Creates new form mainframe
     */
    public mainframe() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this cod new mainframe().setVisible(true);e. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn3 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AI-X/O");
        setBackground(new java.awt.Color(0, 0, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        setForeground(new java.awt.Color(51, 51, 51));
        setLocation(new java.awt.Point(800, 300));

        btn3.setBackground(new java.awt.Color(0, 0, 255));
        btn3.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn1.setBackground(new java.awt.Color(0, 0, 255));
        btn1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(0, 0, 255));
        btn2.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn5.setBackground(new java.awt.Color(0, 0, 255));
        btn5.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setBackground(new java.awt.Color(0, 0, 255));
        btn6.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn4.setBackground(new java.awt.Color(0, 0, 255));
        btn4.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn9.setBackground(new java.awt.Color(0, 0, 255));
        btn9.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn8.setBackground(new java.awt.Color(0, 0, 255));
        btn8.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn7.setBackground(new java.awt.Color(0, 0, 255));
        btn7.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    char[][] Board = {{' ', ' ', ' '},
    {' ', ' ', ' '},
    {' ', ' ', ' '}};
    char player = 'X';
    cheaker c = new cheaker();
    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here: btn1.setText(String.valueOf(player));
        Board[0][2] = player;
        int r = c.minimax(Board, 100, false, true);
        btn1.setText(String.valueOf(Board[0][0]));
        btn2.setText(String.valueOf(Board[0][1]));
        btn3.setText(String.valueOf(Board[0][2]));
        btn4.setText(String.valueOf(Board[1][0]));
        btn5.setText(String.valueOf(Board[1][1]));
        btn6.setText(String.valueOf(Board[1][2]));
        btn7.setText(String.valueOf(Board[2][0]));
        btn8.setText(String.valueOf(Board[2][1]));
        btn9.setText(String.valueOf(Board[2][2]));
        int res = c.checkWinner(Board);
        if (res == 2) {
            //System.out.println("x win");
            JOptionPane.showMessageDialog(null, "x win");
//   
        new mainframe().setVisible(true);        }
        if (res == -2) {
            //System.out.println("o win");
             JOptionPane.showMessageDialog(null, "o win");
//              System.exit(0);
 new mainframe().setVisible(true);        }
        if (res == 0) {
        //    System.out.println("no win");
         JOptionPane.showMessageDialog(null, "draw");
//          System.exit(0);
 new mainframe().setVisible(true);        }
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        btn1.setText(String.valueOf(player));
        Board[0][0] = player;
        c.minimax(Board, 100, false, true);
        btn1.setText(String.valueOf(Board[0][0]));
        btn2.setText(String.valueOf(Board[0][1]));
        btn3.setText(String.valueOf(Board[0][2]));
        btn4.setText(String.valueOf(Board[1][0]));
        btn5.setText(String.valueOf(Board[1][1]));
        btn6.setText(String.valueOf(Board[1][2]));
        btn7.setText(String.valueOf(Board[2][0]));
        btn8.setText(String.valueOf(Board[2][1]));
        btn9.setText(String.valueOf(Board[2][2]));
        int res = c.checkWinner(Board);
        if (res == 2) {
            //System.out.println("x win");
            JOptionPane.showMessageDialog(null, "x win");
//         System.exit(0);
 new mainframe().setVisible(true);        }
        if (res == -2) {
            //System.out.println("o win");
             JOptionPane.showMessageDialog(null, "o win");
//              System.exit(0);
 new mainframe().setVisible(true);        }
        if (res == 0) {
        //    System.out.println("no win");
         JOptionPane.showMessageDialog(null, "draw");
//          System.exit(0);
          new mainframe().setVisible(true);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed


 btn1.setText(String.valueOf(player));
        Board[0][1] = player;
        int r = c.minimax(Board, 100, false, true);
        btn1.setText(String.valueOf(Board[0][0]));
        btn2.setText(String.valueOf(Board[0][1]));
        btn3.setText(String.valueOf(Board[0][2]));
        btn4.setText(String.valueOf(Board[1][0]));
        btn5.setText(String.valueOf(Board[1][1]));
        btn6.setText(String.valueOf(Board[1][2]));
        btn7.setText(String.valueOf(Board[2][0]));
        btn8.setText(String.valueOf(Board[2][1]));
        btn9.setText(String.valueOf(Board[2][2]));
        int res = c.checkWinner(Board);
        if (res == 2) {
            //System.out.println("x win");
            JOptionPane.showMessageDialog(null, "x win");
//             System.exit(0);
              new mainframe().setVisible(true);
        }
        if (res == -2) {
            //System.out.println("o win");
             JOptionPane.showMessageDialog(null, "o win");
//              System.exit(0);
              new mainframe().setVisible(true);        }
        if (res == 0) {
        //    System.out.println("no win");
         new mainframe().setVisible(true);
         JOptionPane.showMessageDialog(null, "draw");
//          System.exit(0);
      new mainframe().setVisible(true);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
       
        
 btn1.setText(String.valueOf(player));
        Board[1][1] = player;
        int r = c.minimax(Board, 100, false, true);
        btn1.setText(String.valueOf(Board[0][0]));
        btn2.setText(String.valueOf(Board[0][1]));
        btn3.setText(String.valueOf(Board[0][2]));
        btn4.setText(String.valueOf(Board[1][0]));
        btn5.setText(String.valueOf(Board[1][1]));
        btn6.setText(String.valueOf(Board[1][2]));
        btn7.setText(String.valueOf(Board[2][0]));
        btn8.setText(String.valueOf(Board[2][1]));
        btn9.setText(String.valueOf(Board[2][2]));
        int res = c.checkWinner(Board);
         if (res == 2) {
            //System.out.println("x win");
            JOptionPane.showMessageDialog(null, "x win");
//             System.exit(0);
            new mainframe().setVisible(true);
         }
        if (res == -2) {
            //System.out.println("o win");
             JOptionPane.showMessageDialog(null, "o win");
//              System.exit(0);
           new mainframe().setVisible(true);
        
        }
        if (res == 0) {
        //    System.out.println("no win");
         JOptionPane.showMessageDialog(null, "draw");
//          System.exit(0);
         new mainframe().setVisible(true);
        }

// TODO add your handling code here:
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
         btn1.setText(String.valueOf(player));
        Board[1][2] = player;
        int r = c.minimax(Board, 100, false, true);
        btn1.setText(String.valueOf(Board[0][0]));
        btn2.setText(String.valueOf(Board[0][1]));
        btn3.setText(String.valueOf(Board[0][2]));
        btn4.setText(String.valueOf(Board[1][0]));
        btn5.setText(String.valueOf(Board[1][1]));
        btn6.setText(String.valueOf(Board[1][2]));
        btn7.setText(String.valueOf(Board[2][0]));
        btn8.setText(String.valueOf(Board[2][1]));
        btn9.setText(String.valueOf(Board[2][2]));
        int res = c.checkWinner(Board);
       if (res == 2) {
            //System.out.println("x win");
            JOptionPane.showMessageDialog(null, "x win");
//             System.exit(0);
                   new mainframe().setVisible(true);
       }
        if (res == -2) {
            //System.out.println("o win");
             JOptionPane.showMessageDialog(null, "o win");
//              System.exit(0);
              new mainframe().setVisible(true);
        }
        if (res == 0) {
        //    System.out.println("no win");
         JOptionPane.showMessageDialog(null, "draw");
//          System.exit(0);
        new mainframe().setVisible(true);
        }
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
         btn1.setText(String.valueOf(player));
        Board[1][0] = player;
        int r = c.minimax(Board, 100, false, true);
        btn1.setText(String.valueOf(Board[0][0]));
        btn2.setText(String.valueOf(Board[0][1]));
        btn3.setText(String.valueOf(Board[0][2]));
        btn4.setText(String.valueOf(Board[1][0]));
        btn5.setText(String.valueOf(Board[1][1]));
        btn6.setText(String.valueOf(Board[1][2]));
        btn7.setText(String.valueOf(Board[2][0]));
        btn8.setText(String.valueOf(Board[2][1]));
        btn9.setText(String.valueOf(Board[2][2]));
        int res = c.checkWinner(Board);
       if (res == 2) {
            //System.out.println("x win");
            JOptionPane.showMessageDialog(null, "x win");
//             System.exit(0);
           new mainframe().setVisible(true);
        }
        if (res == -2) {
            //System.out.println("o win");
             JOptionPane.showMessageDialog(null, "o win");
//              System.exit(0);
              new mainframe().setVisible(true);
        }
        if (res == 0) {
        //    System.out.println("no win");
         JOptionPane.showMessageDialog(null, "draw");
//          System.exit(0);
           new mainframe().setVisible(true);
        }
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
         btn1.setText(String.valueOf(player));
        Board[2][2] = player;
        int r = c.minimax(Board, 100, false, true);
        btn1.setText(String.valueOf(Board[0][0]));
        btn2.setText(String.valueOf(Board[0][1]));
        btn3.setText(String.valueOf(Board[0][2]));
        btn4.setText(String.valueOf(Board[1][0]));
        btn5.setText(String.valueOf(Board[1][1]));
        btn6.setText(String.valueOf(Board[1][2]));
        btn7.setText(String.valueOf(Board[2][0]));
        btn8.setText(String.valueOf(Board[2][1]));
        btn9.setText(String.valueOf(Board[2][2]));
        int res = c.checkWinner(Board);
        if (res == 2) {
            //System.out.println("x win");
            JOptionPane.showMessageDialog(null, "x win");
//             System.exit(0);
            new mainframe().setVisible(true);
        }
        if (res == -2) {
            //System.out.println("o win");
             JOptionPane.showMessageDialog(null, "o win");
//              System.exit(0);
               new mainframe().setVisible(true);
        }
        if (res == 0) {
        //    System.out.println("no win");
         JOptionPane.showMessageDialog(null, "draw");
//          System.exit(0);
         new mainframe().setVisible(true);
        }
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
         btn1.setText(String.valueOf(player));
        Board[2][1] = player;
        int r = c.minimax(Board, 100, false, true);
        btn1.setText(String.valueOf(Board[0][0]));
        btn2.setText(String.valueOf(Board[0][1]));
        btn3.setText(String.valueOf(Board[0][2]));
        btn4.setText(String.valueOf(Board[1][0]));
        btn5.setText(String.valueOf(Board[1][1]));
        btn6.setText(String.valueOf(Board[1][2]));
        btn7.setText(String.valueOf(Board[2][0]));
        btn8.setText(String.valueOf(Board[2][1]));
        btn9.setText(String.valueOf(Board[2][2]));
        int res = c.checkWinner(Board);
       if (res == 2) {
            //System.out.println("x win");
            JOptionPane.showMessageDialog(null, "x win");
//             System.exit(0);
            new mainframe().setVisible(true);
        }
        if (res == -2) {
            //System.out.println("o win");
             JOptionPane.showMessageDialog(null, "o win");
//              System.exit(0);
              new mainframe().setVisible(true);
        }
        if (res == 0) {
        //    System.out.println("no win");
         JOptionPane.showMessageDialog(null, "draw");
//          System.exit(0);
          new mainframe().setVisible(true);
        }
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here
         btn1.setText(String.valueOf(player));
        Board[2][0] = player;
        int r = c.minimax(Board, 100, false, true);
        btn1.setText(String.valueOf(Board[0][0]));
        btn2.setText(String.valueOf(Board[0][1]));
        btn3.setText(String.valueOf(Board[0][2]));
        btn4.setText(String.valueOf(Board[1][0]));
        btn5.setText(String.valueOf(Board[1][1]));
        btn6.setText(String.valueOf(Board[1][2]));
        btn7.setText(String.valueOf(Board[2][0]));
        btn8.setText(String.valueOf(Board[2][1]));
        btn9.setText(String.valueOf(Board[2][2]));
        int res = c.checkWinner(Board);
        if (res == 2) {
            //System.out.println("x win");
            JOptionPane.showMessageDialog(null, "x win");
//             System.exit(0);
           new mainframe().setVisible(true);
        }
        if (res == -2) {
            //System.out.println("o win");
             JOptionPane.showMessageDialog(null, "o win");
//              System.exit(0);
               new mainframe().setVisible(true);
        }
        if (res == 0) {
        //    System.out.println("no win");
         JOptionPane.showMessageDialog(null, "draw");
//          System.exit(0);
          new mainframe().setVisible(true);
        }
    }//GEN-LAST:event_btn7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new mainframe().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    // End of variables declaration//GEN-END:variables
}
